name: basic-sequence-trimmer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - nextflow=23.10.0
  - yaml=0.2.5
  - chopper=0.6.0
  - hostile=0.4.0
  - bbmap=39.01
  - porechop=0.2.4
  - multiqc=1.14